apiVersion: v1
kind: Pod
metadata: 
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: kavyamsrini/my-app1:2.0.0
      ports:
        - containerPort: 8080
