- name: installin tomcat
  hosts: webservers
  gather_facts: true
  become_user: root
  become: yes
  
  vars:
    default: /home/ec2-user
    scontext: /home/ec2-user/apache-tomcat-9.0.65/webapps/manager/META-INF/context.xml
    stomcatusers: /home/ec2-user/apache-tomcat-9.0.65/conf/tomcat-users.xml
  tasks:
    - name: make directory
      file: 
         path: "{{default}}"
         state: directory
    - name: updating os packages
      shell: yum update -y
      args:
        warn: false
    - name: installing tree
      shell: yum install tree -y
      args:
         warn: false
    - name: installing java-8
      yum:
        name: "{{packages}}"
      vars:
        packages:
        - java-1.8.0-openjdk
    - name: tomcat archive download
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
        dest: "{{default}}"
    - name: untaring archive
      command: tar -C "{{default}}" -zvxf /home/ec2-user/apache-tomcat-9.0.65.tar.gz
      args:
        warn: false
    - name: starting_tomcat
      shell: nohup /home/ec2-user/apache-tomcat-9.0.65/bin/startup.sh
    - name: copy war file
      shell: wget http://18.237.234.221:8081/repository/simple-app/com/maven/bt/SimpleWebApplication/9.1.14/SimpleWebApplication-9.1.14.war -P /home/ec2-user/apache-tomcat-9.0.65/webapps
    - name: "check the status of the remote server from localhost"
      uri:
    	  url: "{{ http://18.237.234.221:8081 }}"
    	  method: GET
    	  timeout: 30
    	  return_content: yes
  	    register: out

    - name: Print the msg
      debug:
    	  msg: "{{ out }}"
